development:
 adapter: mysql2
 encoding: utf8
 database: railsforce_dev
 pool: 5
 username: root
 password:

test:
 adapter: mysql2
 encoding: utf8
 database: railsforce_test
 pool: 5
 username: root
 password:


production:
 adapter: mysql2
 encoding: utf8
 database: railsforce_prod
 pool: 5
 username: root
 password: